project:
  type: website

website:
  title: "Sahiti's musings"
  site-url: https://sahiti.nallamudi.com
  description: Sahiti's book reviews 
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sahitisn
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com/in/sahitisn

format:
  html:
    theme: vapor
    css: styles.css

editor: visual

