---
title: "The Arc of a Scythe by Neil Shusterman"
author: "Sahiti Nallamudi"
date: "2023-01-03"
categories: [books]
---

What a way to kick off the new year! We've spent the past two years contemplating life as we know it, and it seems fitting to enter 2023, a year that should be free of these shackles, with a reminder of all that we've learned condensed into a trilogy. A companion novel has been released recently, but given the long hold wait, I don't think I'll be able to read it any time soon. Nevertheless, the trilogy itself gives a well-rounded conclusion, and though I do want to continue inhabiting that world, I have no hard feelings after leaving it.

Far into the future, the internet cloud has evolved into the Thunderhead, an AI that presides over the world with it's just and compassionate hands, making only correct decisions and keeping the world running long past our date of death. Disease has been eradicated, and with it, death, though groups of people called *scythes* keep the population in check by "gleaning" -- killing -- a certain number of people, a quota provided by the Thunderhead. But like any human organization, it is riddled with corruption, and since the Thunderhead leaves matters of life and death in the hands of the humans who experience it, it cannot make direct change. So it's up to Citra and Rowan, two scythe apprentices, who each become scythes in their own way, to make change.

I know we're all expecting a romance between them, because that's what's expected in a book like this, but I honestly wish it would've been left out -- it's boring, shallow, and under-developed. Maybe it's just me, but I can't see a world-shattering, mountain-moving love from two teenagers who know next to nothing about each other. The romance subplot between them feels thin, especially compared to the romance we see later between two elder scythes, a truly forbidden love and as deep as they are old. Besides that bogging down the novels, the story arc (pun not intended) itself is engaging and well-thought-out, even and interesting, the twists both unexpected and consistent with the characters. The villain is someone we may have collectively seen in the past few years, and so our hatred for him may be just as strong. Take your time with this series, as the characters don't value the time they have. The prose explores just how much we lose when we lose the light of life in contrast to the darkness of death, and what the consequences are when we try, corruptly, to get it back. The trilogy is compelling and considerate, an analysis of humanity and our downfalls and upsides -- a thoughtful start to a new year. Count it.
