---
title: "The Raven Cycle by Maggie Stiefvater"
author: "Sahiti Nallamudi"
date: "2022-12-28"
categories: [books]
---

To say this year was busy is an understatement, and nothing proves it more than these last few vestiges of 2022. In the midst of chaos, there's no better way to end it with the Raven Cycle, a fantasy trilogy with one companion novel from my newly beloved Maggie Stiefvater, an author who seems to me to be blessed by some unknown god to write like she does. Ladies and gentlemen, I *ate* these novels.

Let me preface by saying the first book had been left open to page 10 for about six months, if I'm being generous -- a combination of work, school, studying, distraction, exhaustion, and, I'll admit, a little laziness made sure the book collected dust in the internet cloud it rented out for half a year on my iPad. And then, the end of the school coincided with the release of test scores (can I get a collective, *ugh standardized testing*?) and most of my other obligations faded away for a blissful two weeks, the first five days of which I spent blowing through this series. You heard that right -- five days, for four books. I wasn't kidding when I said I ate them. Meet Blue Sargent, a girl so human she feels otherworldly, and every instinct you have about her will be correct. Gansey, Mr. Richie Rich with a heart of gold and eyes of steel -- a boy broken in all the wrong places. Adam Parrish, a character who read to me like reading my own diary -- too similar to be real, too different to care. Ronan Lynch, my favorite type of character; broken beyond repair but trying anyway.

Gansey and his merry thieves are in search of a Welsh king who's been asleep for centuries, outwardly telling people they want the wish he'll grant when he wakes, but really just doing it because their souls tell them they must. But Blue knows something they don't -- Gansey will die by the year's end. suddenly, their quest has a deadline no one but her knows about, and Blue's deadline might overlap with it -- she's cursed to kill her true love with a kiss, and she'll fall in love by this year. This plotline is fairly predictable, but the implications for their main plotline are endless and twisty, unimaginable to anyone but Stiefvater, in her heavy, soft, and poignant prose, tying a leash around your neck while you bounce merrily along.

I'll leave the blurbs to tell you more about the story, but these books are the kinds that burrow into your heart to tug at your arteries. Magic doesn't seem any more imaginary than phones, which seem out of place and out of time in an ageless story woven with dreams. If you have a few days to spare, I recommend flying through this series as I did. They're books that will stay with you forever, even when you forget them. Like a dream.
